name: inspector_gadget
description: Open Multi-Modal Personal Assistant
version: 1.0.2+1
publish_to: none

environment:
  sdk: ^3.5.3

dependency_overrides:
  collection: ^1.19.0  # Flutter SDK (flutter_test pinned it)
  js: ^0.7.1  # media_kit vs speech_to_text

dependencies:
  adaptive_dialog: ^2.2.0
  assorted_layout_widgets: ^9.0.2
  camera: ^0.11.0+2
  collection: ^1.19.0
  country_flags: ^3.0.0
  dart_helper_utils: ^2.7.0
  daylight: ^3.1.0
  file_picker: ^8.1.2
  fl_location: ^4.1.0+1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_easy_animations: ^0.0.2
  flutter_layout_grid: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  flutter_tts: ^4.0.2
  gap: ^3.0.1
  get_it: ^7.7.0
  google_generative_ai: ^0.4.6
  heart_rate_flutter: ^0.0.2
  http: ^1.2.2
  intl: ^0.19.0
  listview_utils_plus: ^0.0.3
  media_kit: ^1.1.11
  media_kit_libs_audio: ^1.0.5
  mime: ^1.0.6
  number_selector: ^1.0.7
  objectbox: ^4.0.2
  objectbox_flutter_libs: ^4.0.2
  path: ^1.9.0
  path_provider: ^2.1.4
  pref: ^2.8.0
  record: ^5.1.2
  smooth_page_indicator: ^1.2.0+3
  speech_to_text: ^7.0.0
  statemachine: ^3.3.1
  strings: ^3.1.2
  translator: ^1.0.0
  tuple: ^2.0.2
  video_player: ^2.9.1
  watch_it: ^1.4.2

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  objectbox_generator: ^4.0.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
