name: inspector_gadget
description: Open Multi-Modal Personal Assistant
version: 1.0.2+1
publish_to: none

environment:
  sdk: ^3.5.6

dependency_overrides:
  collection: ^1.19.1  # Flutter SDK (flutter_test pinned it)
  mime: ^2.0.0
  path: ^1.9.1  # Flutter SDK (flutter_test pinned it)

dependencies:
  adaptive_dialog: ^2.3.0
  assorted_layout_widgets: ^10.0.4
  camera: ^0.11.0+2
  cloud_functions: ^5.2.0
  collection: ^1.19.0
  country_flags: ^3.1.0
  dart_helper_utils: ^3.3.0
  daylight: ^3.1.0
  file_picker: ^8.1.6
  firebase_app_check: ^0.3.1+7
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  firebase_ui_storage: ^2.1.0
  firebase_vertexai: ^1.0.4
  fl_location: ^5.0.0
  flex_color_scheme: ^8.0.2
  flutter:
    sdk: flutter
  flutter_easy_animations: ^0.0.2
  flutter_layout_grid: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  flutter_tts: ^4.2.0
  gap: ^3.0.1
  get_it: ^8.0.3
  heart_rate_flutter: ^0.0.2
  http: ^1.2.2
  intl: ^0.19.0
  listview_utils_plus: ^0.0.3
  media_kit: ^1.1.11
  media_kit_libs_audio: ^1.0.5
  mime: ^2.0.0
  number_selector: ^1.0.7
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  path: ^1.9.1
  path_provider: ^2.1.5
  pref: ^2.8.0
  progress_indicators: ^1.0.0
  record: ^5.2.0
  smooth_page_indicator: ^1.2.0+3
  speech_to_text: ^7.0.0
  statemachine: ^3.3.1
  strings: ^3.1.2
  translator: ^1.0.3+1
  tuple: ^2.0.2
  video_player: ^2.9.2
  watch_it: ^1.6.1

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  objectbox_generator: ^4.0.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
