name: inspector_gadget
description: Inspector Gadget
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.4

dependency_overrides:
  js: ^0.7.1  # Due to media_kit vs speech_to_text collision

dependencies:
  bloc: ^8.1.3
  dart_helper_utils: ^2.1.0
  daylight: ^3.1.0
  file_picker: ^8.0.6
  fl_location: ^4.0.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_easy_animations: ^0.0.2
  flutter_layout_grid: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^4.0.2
  google_generative_ai: ^0.4.3
  heart_rate_flutter: ^0.0.2
  http: ^1.2.2
  intl: ^0.19.0
  media_kit: ^1.1.10
  media_kit_libs_audio: ^1.0.4
  path: ^1.9.0
  path_provider: ^2.1.3
  pref: ^2.8.0
  record: ^5.1.2
  speech_to_text: ^6.6.2
  statemachine: ^3.3.1
  tuple: ^2.0.2

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
