name: inspector_gadget
description: Inspector Gadget Test
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.3
  dart_helper_utils: ^2.0.0
  daylight: ^3.1.0
  fl_location: ^3.1.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_easy_animations: ^0.0.2
  flutter_layout_grid: ^2.0.0
  flutter_localizations:
    sdk: flutter
  google_generative_ai: ^0.4.3
  heart_rate_flutter: ^0.0.2
  http: ^1.2.1
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.3
  pref: ^2.8.0
  record:
    git:
      url: https://github.com/CsabaConsulting/record.git
      path: record
  speech_to_text: ^6.6.2
  statemachine: ^3.3.1

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
